ifndef TARGET_KERNEL_USE
TARGET_KERNEL_USE=4.9
endif

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1073741312
BOARD_USERDATAIMAGE_PARTITION_SIZE := 5456789504
BOARD_CACHEIMAGE_PARTITION_SIZE := 1073741312
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4

BOARD_PRIVATEIMAGE_PARTITION_SIZE := 52428800
BOARD_SECURESTORE_PARTITION_SIZE:= 8388608
BOARD_BACKUPIMAGE_PARTITION_SIZE := 838860800
BOARD_FLASH_BLOCK_SIZE := 512

BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true

TARGET_NO_BOOTLOADER := false
TARGET_BOOTLOADER_IS_2ND = true
TARGET_NO_KERNEL := false

BOARD_KERNEL_CMDLINE := androidboot.hardware=poplar androidboot.selinux=permissive mmz=ddr,0,0,60M firmware_class.path=/system/etc/firmware

TARGET_NO_RECOVERY := true
TARGET_NO_RADIOIMAGE := true

TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a9
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi

TARGET_USES_64_BIT_BINDER := true

ARCH_ARM_HAVE_TLS_REGISTER := true

BOARD_USES_GENERIC_AUDIO := true

# no hardware camera
USE_CAMERA_STUB := true

USE_OPENGL_RENDERER := true

WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_bcmdhd
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_bcmdhd
BOARD_WLAN_DEVICE := bcmdhd


TARGET_BOARD_PLATFORM := poplar
TARGET_BOOTLOADER_BOARD_NAME := poplar

BOARD_SEPOLICY_DIRS := device/hisilicon/poplar/sepolicy
